prefix g1: <http://data-gov.tw.rpi.edu/vocab/Dataset_401>
prefix g2: <http://data-gov.tw.rpi.edu/vocab/Dataset_403>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?year sum(xsd:double (?value1)) sum(xsd:double (?value2))
WHERE
{

  {
     GRAPH g1: {
        ?s <http://data-gov.tw.rpi.edu/vocab/p/401/agency_name> "Christopher Columbus Fellowship Foundation".
        ?s ?year ?value1 .
        filter (regex(?year,"num(197[6-9]|19[89][0-9]|2[0-9]+)"))
     }
   } UNION {
     GRAPH g2: {
       ?s2 <http://data-gov.tw.rpi.edu/vocab/p/401/agency_name> "Christopher Columbus Fellowship Foundation" .
       ?s2 ?year ?value2 .
       filter (regex(?year,"num(197[6-9]|19[89][0-9]|2[0-9]+)"))
     }
   }
}
group by ?year
order by ?year
